// packages/umbra/src/solid/use-bootstrap.ts
import { onMount } from 'solid-js';
import type { Bootstrap } from '../core/create-bootstrap.js';
import type { RunSnapshot } from '../core/run-observer.js';
import type { AnyStep } from '../core/types.js';
import { fromStore } from './from-store.js';

/**
 * Run a bootstrap and track it in a signal.
 *
 * **Returns an accessor, so do not destructure it.** `const snapshot = useBootstrap(boot)` then
 * `snapshot().stage`; pulling `stage` out once reads the value at that instant and never again,
 * which is the one difference between this binding and React's.
 *
 * The observer lives on the bootstrap rather than on the component, so however many components call
 * this, the bootstrap runs once and they all read the same snapshot.
 *
 * @example
 * const snapshot = useBootstrap(boot);
 * return <Show when={snapshot().stage === 'settled'} fallback={<Splash />}>{...}</Show>;
 */
export function useBootstrap<TSteps extends readonly AnyStep[]>(
  boot: Bootstrap<TSteps>
): () => RunSnapshot<TSteps> {
  const observer = boot.observe();
  onMount(() => {
    observer.start();
  });
  return fromStore(observer.store);
}

// src/react/use-bootstrap.ts
import { useEffect, useSyncExternalStore } from 'react';
import type { Bootstrap } from '../core/create-bootstrap.js';
import type { RunSnapshot } from '../core/run-observer.js';
import type { AnyStep } from '../core/types.js';

/**
 * Run a bootstrap and re-render as it progresses.
 *
 * The observer lives on the bootstrap rather than on the component, so however many components call
 * this, the bootstrap runs once and they all read the same snapshot. That is also why there is no
 * cleanup here: the observer's lifetime is the bootstrap's, and disposing it when one component
 * unmounted would blind the others.
 *
 * `start` is idempotent, which is what makes the effect safe under StrictMode's double invocation.
 *
 * @example
 * function Shell({ boot }: { boot: Bootstrap<typeof steps> }) {
 *   const { stage, outcome } = useBootstrap(boot);
 *   if (stage !== 'settled') { return <Splash />; }
 *   return outcome.status === 'blocked' ? <SignIn /> : <App />;
 * }
 */
export function useBootstrap<TSteps extends readonly AnyStep[]>(
  boot: Bootstrap<TSteps>
): RunSnapshot<TSteps> {
  const observer = boot.observe();

  useEffect(() => {
    observer.start();
  }, [observer]);

  return useSyncExternalStore(observer.store.subscribe, observer.store.get, observer.store.get);
}
